language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
before_script:
  - composer install
  - composer dump-autoload
script:
  - vendor/bin/phpunit Tests/
notfications:
  email:
    recipients:
      - milonas.ko@gmail.com
    on_success: always
    on_failure: always
