language: php
php:
  - 7.2
before_script:
  - composer install
  - composer dump-autoload
script:
  - make test
notfications:
  email:
    recipients:
      - milonas.ko@gmail.com
    on_success: always
    on_failure: always
